/// Lanna rules data containing mapping and grammatic rules for Tai Tham script.
class LannaConsonantInfo {
  final String thaiChar;
  final String lannaChar;
  final int groupIndex; // 1: กะ, 2: จะ, 3: ฏะ, 4: ตะ, 5: ปะ, 0: เศษวรรค
  final int positionInGroup; // 1-5 ในวรรค

  const LannaConsonantInfo({
    required this.thaiChar,
    required this.lannaChar,
    required this.groupIndex,
    required this.positionInGroup,
  });
}

class LannaRulesData {
  /// พยัญชนะ 33 ตัว และวรรคสังกัดตามกฎพยัญชนะสังโยค (บาลี-สันสกฤต)
  static const List<LannaConsonantInfo> consonants = [
    // วรรค กะ (ฐานเพดานอ่อน)
    LannaConsonantInfo(thaiChar: 'ก', lannaChar: '\u1A20', groupIndex: 1, positionInGroup: 1),
    LannaConsonantInfo(thaiChar: 'ข', lannaChar: '\u1A21', groupIndex: 1, positionInGroup: 2),
    LannaConsonantInfo(thaiChar: 'ค', lannaChar: '\u1A23', groupIndex: 1, positionInGroup: 3),
    LannaConsonantInfo(thaiChar: 'ฅ', lannaChar: '\u1A24', groupIndex: 1, positionInGroup: 4),
    LannaConsonantInfo(thaiChar: 'ฆ', lannaChar: '\u1A25', groupIndex: 1, positionInGroup: 4),
    LannaConsonantInfo(thaiChar: 'ง', lannaChar: '\u1A26', groupIndex: 1, positionInGroup: 5),

    // วรรค จะ (ฐานเพดานแข็ง)
    LannaConsonantInfo(thaiChar: 'จ', lannaChar: '\u1A27', groupIndex: 2, positionInGroup: 1),
    LannaConsonantInfo(thaiChar: 'ฉ', lannaChar: '\u1A28', groupIndex: 2, positionInGroup: 2),
    LannaConsonantInfo(thaiChar: 'ช', lannaChar: '\u1A2A', groupIndex: 2, positionInGroup: 3),
    LannaConsonantInfo(thaiChar: 'ซ', lannaChar: '\u1A2B', groupIndex: 2, positionInGroup: 4),
    LannaConsonantInfo(thaiChar: 'ฌ', lannaChar: '\u1A2C', groupIndex: 2, positionInGroup: 4),
    LannaConsonantInfo(thaiChar: 'ญ', lannaChar: '\u1A2D', groupIndex: 2, positionInGroup: 5),

    // วรรค ฏะ (ฐานปุ่มเหงือก)
    LannaConsonantInfo(thaiChar: 'ฏ', lannaChar: '\u1A30', groupIndex: 3, positionInGroup: 1),
    LannaConsonantInfo(thaiChar: 'ฐ', lannaChar: '\u1A31', groupIndex: 3, positionInGroup: 2),
    LannaConsonantInfo(thaiChar: 'ฑ', lannaChar: '\u1A33', groupIndex: 3, positionInGroup: 3),
    LannaConsonantInfo(thaiChar: 'ฒ', lannaChar: '\u1A33', groupIndex: 3, positionInGroup: 4),
    LannaConsonantInfo(thaiChar: 'ณ', lannaChar: '\u1A34', groupIndex: 3, positionInGroup: 5),
    LannaConsonantInfo(thaiChar: 'ฎ', lannaChar: '\u1A32', groupIndex: 3, positionInGroup: 1),

    // วรรค ตะ (ฐานฟัน)
    LannaConsonantInfo(thaiChar: 'ด', lannaChar: '\u1A35', groupIndex: 4, positionInGroup: 1),
    LannaConsonantInfo(thaiChar: 'ต', lannaChar: '\u1A36', groupIndex: 4, positionInGroup: 1),
    LannaConsonantInfo(thaiChar: 'ถ', lannaChar: '\u1A37', groupIndex: 4, positionInGroup: 2),
    LannaConsonantInfo(thaiChar: 'ท', lannaChar: '\u1A38', groupIndex: 4, positionInGroup: 3),
    LannaConsonantInfo(thaiChar: 'ธ', lannaChar: '\u1A39', groupIndex: 4, positionInGroup: 4),
    LannaConsonantInfo(thaiChar: 'น', lannaChar: '\u1A3B', groupIndex: 4, positionInGroup: 5),

    // วรรค ปะ (ฐานริมฝีปาก)
    LannaConsonantInfo(thaiChar: 'บ', lannaChar: '\u1A3C', groupIndex: 5, positionInGroup: 1),
    LannaConsonantInfo(thaiChar: 'ป', lannaChar: '\u1A3D', groupIndex: 5, positionInGroup: 1),
    LannaConsonantInfo(thaiChar: 'ผ', lannaChar: '\u1A3F', groupIndex: 5, positionInGroup: 2),
    LannaConsonantInfo(thaiChar: 'ฝ', lannaChar: '\u1A40', groupIndex: 5, positionInGroup: 2),
    LannaConsonantInfo(thaiChar: 'พ', lannaChar: '\u1A41', groupIndex: 5, positionInGroup: 3),
    LannaConsonantInfo(thaiChar: 'ฟ', lannaChar: '\u1A42', groupIndex: 5, positionInGroup: 4),
    LannaConsonantInfo(thaiChar: 'ภ', lannaChar: '\u1A43', groupIndex: 5, positionInGroup: 4),
    LannaConsonantInfo(thaiChar: 'ม', lannaChar: '\u1A45', groupIndex: 5, positionInGroup: 5),

    // เศษวรรค (อวรรค)
    LannaConsonantInfo(thaiChar: 'ย', lannaChar: '\u1A46', groupIndex: 0, positionInGroup: 1),
    LannaConsonantInfo(thaiChar: 'ร', lannaChar: '\u1A48', groupIndex: 0, positionInGroup: 2),
    LannaConsonantInfo(thaiChar: 'ล', lannaChar: '\u1A49', groupIndex: 0, positionInGroup: 3),
    LannaConsonantInfo(thaiChar: 'ว', lannaChar: '\u1A4A', groupIndex: 0, positionInGroup: 4),
    LannaConsonantInfo(thaiChar: 'ศ', lannaChar: '\u1A4B', groupIndex: 0, positionInGroup: 5),
    LannaConsonantInfo(thaiChar: 'ษ', lannaChar: '\u1A4C', groupIndex: 0, positionInGroup: 6),
    LannaConsonantInfo(thaiChar: 'ส', lannaChar: '\u1A4D', groupIndex: 0, positionInGroup: 7),
    LannaConsonantInfo(thaiChar: 'ห', lannaChar: '\u1A4E', groupIndex: 0, positionInGroup: 8),
    LannaConsonantInfo(thaiChar: 'ฬ', lannaChar: '\u1A49', groupIndex: 0, positionInGroup: 9),
    LannaConsonantInfo(thaiChar: 'อ', lannaChar: '\u1A53', groupIndex: 0, positionInGroup: 10),
    LannaConsonantInfo(thaiChar: 'ฮ', lannaChar: '\u1A54', groupIndex: 0, positionInGroup: 11),
  ];

  /// สระเดี่ยวและประสมทั่วไป
  static const Map<String, String> generalVowels = {
    'ะ': '\u1A61', 'า': '\u1A63', 'ิ': '\u1A65', 'ี': '\u1A66', 'ึ': '\u1A67', 'ื': '\u1A68',
    'ุ': '\u1A69', 'ู': '\u1A6A', 'เ': '\u1A6E', 'แ': '\u1A6F', 'โ': '\u1A70', 'ไ': '\u1A71',
    'ใ': '\u1A72', 'ั': '\u1A62', '็': '\u1A7C',
  };

  /// สระตามภาษาบาลี (สระสำเร็จรูปที่ห้ามนำไปประกอบเป็นสระอื่นๆ)
  static const Set<String> paliAbsoluteVowels = {
    'อะ', 'อา', 'อิ', 'อี', 'อุ', 'อู', 'เอ', 'โอ'
  };

  /// ตัวสะกดหลัก 6 แม่
  static const Set<String> standardSpellingConsonants = {
    'ก', 'ง', 'ด', 'บ', 'ม', 'น'
  };

  /// ตัวสะกดพิเศษจากบาลี-สันสกฤต
  static const Set<String> specialSpellingConsonants = {
    'ค', 'ช', 'ญ', 'ฏ', 'ณ', 'ต', 'ท', 'พ', 'ภ', 'ล', 'ศ'
  };

  /// ตารางคำเฉพาะเขียน/อ่านพิเศษ และการเทียบเสียงคำถิ่น
  static const Map<String, String> irregularSpellingMap = {
    'สวัสดี': 'ᩈ᩠ᩅᩢᩈ᩠ᨯᩦ',
    'ล้านนา': 'ᩃ᩶ᩣᨶᨶᩣ',
    'ข้าว': 'ᨡ᩶ᩣ',
    'ขนม': 'ᨡ᩶ᩣᩉ᩠ᨶᨾ',
    'วัด': 'ᩅ᩠ᨯ',
    'วัดพระสิงห์': 'ᩅ᩠ᨯᨻᩕᩈᩥᨦ᩠ᨻ᩺',
    'กษัตริย์': 'ᨠᩈᨲᩕ᩠ᨿ᩺',
    'สันติ': 'ᩈ᩠ᨶ᩠ᨲᩥ',
    'อรหันต์': 'ᩋᩁᩉ᩠ᨶ᩠ᨲ᩺',
    'เชียงใหม่': 'ᨩ᩠ᨿᨦᩲᩉ᩠ᨾ᩵',
    'ลำพูน': 'ᩃᨸᩪ᩠ᨶ',
    'ลำปาง': 'ᩃᩣᩴᨸᩣᨦ',
    'แม่ฮ่องสอน': 'ᩯᨾ᩵ᩉ᩵ᩬᨦᩈᩬ᩠ᨶ',
    'เชียงราย': 'ᨩ᩠ᨿᨦᩁᩣᨿ',
    'พะเยา': 'ᨻᨿᩮᩣ',
    'แพร่': 'ᩯᨻᩕ᩵',
    'น่าน': 'ᨶ᩵ᩣ᩠ᨶ',
    'อุตรดิตถ์': 'ᩋᩩᨲ᩠ᨲᩁᨯᩥᨲ᩠ᨳ᩺',
    'ประตูช้างเผือก': 'ᨲᩪᨩ᩶ᩣᨦᨹᩮᩥᩢᨠ',
    'ช้างเผือก': 'ᨩ᩶ᩣᨦᨹᩮᩥᩢᨠ',
    'ประตู': 'ᨲᩪ',
    'ขี้สัด': 'ᨡᩦ᩶ᩈ᩠ᨯ',
    'ก่ะ': 'ᨠ᩵ᩡ',
    'ผ้าตุ้ม': 'ᨹ᩶ᩣᨲᩩ᩠ᨾ',
    'จามๆ ไอๆ': 'ᨧᩣᨾ᩺',
    'ย้อย': 'ᨿ᩶ᩬᨿ',
    'ปวง': 'ᨸ᩠ᩅᨦ',
    'แบหงาย': 'ᩯᨷᩉ᩠ᨦᩣᨿ',
    'จ่านว่าไป': 'ᨧ᩵ᩣᨶᩅ᩵ᩣᩱᨿ',
    'บ่ามุด': 'ᨷ᩵ᩣᨾᩩᨯ',
    'เข้า': 'ᨡ᩶ᩣ',
    'ตุงผีตาย': 'ᨲᩩᨦᨹᩦᨲᩣᨿ',
    'ละกังเงียง': 'ᩃᩡᨠᩢᨦ᩠ᨦᩦ᩠ᨿᨦ',
    'จักโจ้จักโจ': 'ᨧᩢᨠ᩠ᨧᩰ᩶ᨧᩢᨠ᩠ᨧᩰ',
    'กำปือ': 'ᨠᩴ᩠ᨸᩨ',
    'ปะ - ปะ': 'ᨸ',
    'กินหมดกินเสี้ยง': 'ᨠᩥᨶᩉ᩠ᨾᩫᨯᨠᩥᨶᩈ᩠ᨿ᩶ᨦ',
    'หนักข้อน': 'ᩉ᩠ᨶᩢᨠᨡ᩶ᩬᨶ',
    'น้า': 'ᨶ᩶ᩣ',
    'เป็นดีมี่ฮ่าง': 'ᨸᩮ᩠ᨶᨯᩦᨾᩦᩉ᩵ᩣᨦ',
    'ฝนโบกขรพรรษ': 'ᨺᩫᨶᨷᩰᨠᨡᩁᨻᩢᨲ᩠ᨲ',
    'ขันโตกลาว': 'ᨡᩢᨶ᩠ᨲᩰ᩠ᨠᩃᩣ᩠ᩅ',
    'เดาะเข้า': 'ᩮᨯᩣᩡᨡ᩶ᩣ',
    'หนวกหู': 'ᩉ᩠ᨶᩅᨠᩉᩪ',
    'แคว่น': 'ᩯᨣ᩠ᩅ᩵ᨶ',
    'ซ่อมฮู': 'ᩈ᩵ᩬᨾᩉᩪ',
    'คางคาก': 'ᨣᩣᨦᨣᩣᨠ',
    'หัวปลวก': 'ᩉ᩠ᨅᩫᩅᨸ᩠ᩅᨠ',
    'ควัตรูดัง': 'ᨣ᩠ᩅᩢᨲᩁᩪᨯᩢᨦ',
    'กำต่อ': 'ᨠᩴ᩠ᨲᩬ᩵',
    'จี่ดอก': 'ᨧᩦ᩵ᨯᩬᨠ',
    'อุกหยุก': 'ᩋᩩᨠᩉ᩠ᨿᩩᨠ',
    'สะวัด': 'ᩈ᩠ᩅᩢᨯ',
    'ปวด': 'ᨸ᩠ᩅᨯ',
    'สะหมุน': 'ᩈ᩠ᨾᩩᨶ',
    'ปากเปียะ': 'ᨸᩣᨠᨸ᩠ᨿᩡ',
    'ผ่า': 'ᨹ᩵ᩣ',
    'กวักมือ': 'ᨠ᩠ᩅᩢᨠᨾᩨ',
    'เข้าหวิดแลง': 'ᨡ᩶ᩣᩉ᩠ᩅᩥᨯᩯᩃᨦ',
    'หนีบ': 'ᩉ᩠ᨶᩦᨷ',
    'ตุ่มใส': 'ᨲᩩ᩠ᨾᩱᩈ',
    'งวงจ้าง': 'ᨦ᩠ᩅᨦᨩ᩶ᩣᨦ',
    'ยานต่างเต่ง': 'ᨿᩣᨶᨲ᩵ᩣᨦᨲᩮ᩵ᨦ',
    'ไม้สองนาง': 'ᨾᩲ᩶ᩈᩬᨦᨶᩣᨦ',
    'จักกะหลี่': 'ᨧᩢᨠ᩠ᨠᩡᩉ᩠ᩃᩦ',
    'คันได': 'ᨣᩢᨶᩱᨯ',
    'มันฝรั่ง': 'ᨾᩢᨶᨺᩕᩢᨦ',
    'หน้าฮก': 'ᩉ᩠ᨶ᩶ᩣᩫᨠ',
    'ผะตัด': 'ᨹᩡᨲᩢᨯ',
    'จาใด': 'ᨧᩣᩱᨯ',
    'ตอก': 'ᨲᩬᨠ',
    'เขียดแหลว': 'ᨡᩦᨿᨯᩡᩉᩃᩅ',
    'คนไทยล้านนา': 'ᨣᨶ᩠ᨴᩱᩃᩣ᩠ᨶᨶᩣ',
    'ค่าใต้': 'ᨣ᩵ᩣᩱᨲ᩶',
    'คุ้ม': 'ᨣᩩ᩶ᨾ',
    'จ้างซอ': 'ᨧ᩶ᩣᨦᨪᩬ',
    'เจดีย์ทรายสุดส้าว': 'ᨧᩮᨯᩦᨿ᩺ᨪᩣᨿᩈᩩᨯᩈ᩶ᩣᩅ',
    'บัวตอง': 'ᨷ᩠ᩅᨲᩬᨦ',
    'ปี้': 'ᨸᩦ᩶',
    'ปู่เมีย': 'ᨸᩪ᩵ᨾ᩠ᨿ',
    'ก้อ': 'ᨠᩬ᩶',
    'ก๋องตุมเต๊ม': 'ᨠᩬᨦᨲᩩᨾᨲᩮ᩠ᨾ',
    'ก๋องต๊อมแต๊ม': 'ᨠᩬᨦᨲᩬᨾᨲᩯ᩠ᨾ',
    'กลองอืด': 'ᨠᩃᩋᨦᩋᩨ᩠ᨯ',
    'กำเมือง': 'ᨠᩴ᩠ᨾᩨᨦ',
    'ก่ายอง': 'ᨠ᩵ᩣᨿᩬᨦ',
    'กำลื้อ': 'ᨠᩴ᩠ᨃᩨ',
    'กิ๋นตุ๊จั๊ก': 'ᨠᩥᨶᨲᩩ᩶ᨧᩢᨠ',
    'ขะหมุ': 'ᨡᨾᩩ',
    'จ่าหนี': 'ᨧ᩵ᩣᩉ᩠ᨶᩦ',
    'ป้องกันลูกกัน': 'ᨸ᩶ᩬᨦᨠᩢᨶᩃᩪᨠᨠᩢᨶ',
    'เข้าอี่ตู': 'ᨡ᩶ᩣᩋᩦ᩵ᨲᩪ',
    'ตากเหงือกตากหงาย': 'ᨲᩣᨠᩉ᩠ᨦᩨᩋᨠᨲᩣᨠᩉ᩠ᨦᩣᨿ',
    'จุ๋มอกจุ๋มใจ': 'ᨧᩩ᩠ᨾᩋ᩠ᨠᨧᩩ᩠ᨾᩱᨧ',
    'หน่วยตา': 'ᩉ᩠ᨶ᩵ᩅᨿᨲᩣ',
    'ติ้ง': 'ᨲᩥ᩶ᨦ',
    'บ่าเกว่นควาย': 'ᨷ᩵ᩣᨠ᩠ᩅᩯ᩠ᨶᨣ᩠ᩅᩣᨿ',
    'สวดจุ๋มปุ๋ม': 'ᩈ᩠ᩅᨯᨧᩩ᩠ᨾᨸᩩ᩠ᨾ',
    'ผ่าย': 'ᨹ᩵ᩣᨿ',
    'น้ำหัว': 'ᨶ᩶ᩣᩴᩉ᩠ᨅᩫᩅ',
    'ห่วง': 'ᩉ᩠ᩅ᩵ᨦ',
    'บ่าแต่งขี้ไก่': 'ᨷ᩵ᩣᨲᩯ᩵ᨦᨡᩦ᩶ᨠ᩵',
    'อ็อกหนี่อก': 'ᩋᩫᨠᩉ᩠ᨶᩦᩋᩫᨠ',
    'ปู๊น': 'ᨸᩪ᩶ᨶ',
    'หละวงโขงเขต': 'ᩃᩡᩅᨦᨡᩮᨲ',
    'สร้างตัว': 'ᩈᩕ᩶ᩣᨦᨲ᩠ᩅ',
    'สนสะจา': 'ᩈᩫᨶᩈᩡᨧᩣ',
    'ผักจ้อยนาง': 'ᨹᩢᨠᨧ᩶ᩬᨿᨶᩣᨦ',
    'หมดเสี้ยง': 'ᩉ᩠ᨾᩫᨯᩈ᩠ᨿ᩶ᨦ',
    'กรั้น': 'ᨠᩕᩢᨶ',
    'ลัง': 'ᩃᩢᨦ',
    'จบ': 'ᨧᩫᨷ',
    'หน็อกๆ': 'ᩉ᩠ᨶᩬᨠ᩺',
    'ปักป่าว': 'ᨸᩢᨠᨸ᩵ᩣᩅ',
    'หละล่อย': 'ᩃᩡᩃᩬ᩵ᨿ',
    'ขี้หูด': 'ᨡᩦ᩶ᩉᩪᨯ',
    'ออกแดง': 'ᩋᩬᨠᩯᨯᨦ',
    'ก่าง': 'ᨠ᩵ᩣᨦ',
    'ก่ำ': 'ᨠ᩵ᩣᩴ',
    'ชาง': 'ᨩᩣᨦ',
    'บ่าก้อ': 'ᨷ᩵ᩣᨠᩬ᩶',
    'แมงใบ้': 'ᨾᩯᨦᨷᩱ᩶',
    'ขอกเมือง': 'ᨡᩬᨠᨾᩮᩥᨦ',
    'อย่างอั้น': 'ᩋ᩠ᨿ᩵ᩣᨦᩋᩢ᩠ᨶ',
    'เต่า': 'ᨲᩮ᩵ᩣ',
    'ถอน': 'ᨦᩬᨶ',
    'สมเสง': 'ᩈᩫᨾᩈᩮᨦ',
    'หัวล้าน': 'ᩉ᩠ᨅᩫᩅᩃ᩶ᩣᨶ',
    'บ้านห้าง': 'ᨷ᩶ᩣᨶᩉ᩶ᩣᨦ',
    'แก่นหมั้น': 'ᩯᨠ᩠ᨶᩉ᩠ᨾᩢ᩠ᨶ',
    'ใต้': 'ᩱᨲ᩶',
    'เหี้ย': 'ᩉ᩠ᨿᩦ',
    'เข้าต้ม': 'ᨡ᩶ᩣᨲᩫ᩶ᨾ',
    'สะหลึง': 'ᩈ᩠ᩃᩧᨦ',
    'เชือกค่าว': 'ᨩᩨᩋᨠᨣ᩵ᩣᩅ',
    'เหล้าหัวเด็ด': 'ᩉ᩠ᩃ᩶ᩣᩉ᩠ᨅᩫᩅᨯᩮ᩠ᨯ',
    'แว่หั่นแว่นี้': 'ᩯᩅ᩵ᩉ᩠ᨶᩢᩯᩅ᩵ᨶᩦ᩶',
    'หัวบ้าน': 'ᩉ᩠ᨅᩫᩅᨷ᩶ᩣᨶ',
    'ต๊อมน้ำ': 'ᨲᩬᨾᨶ᩶ᩣᩴ',
    'บ่าคอแลน': 'ᨷ᩵ᩣᨣᩬᩯᩃᨶ',
    'ฮากแตกฮากแต่น': 'ᩉᩕᩣᨠᩯᨲᨠᩉᩕᩣᨠᩯᨲᨶ',
    'ต่อย': 'ᨲᩬ᩵ᨿ',
    'สมฤทธิ์': 'ᩈᩫᨾᩁᩥᨴ᩠ᨵᩦ',
    'หัวง๊อก': 'ᩉ᩠ᨅᩫᩅᨦᩬᨠ',
    'ซอมกอ': 'ᨪᩬᨾᨠᩬ',
    'ดำฝืด': 'ᨯᩣᩴᨼᩨᨯ',
    'บอกไฟเตียน': 'ᨷᩬᨠᩱᨼᨲ᩠ᨿᨶ',
    'ของ': 'ᨡᩬᨦ',
    'ขนตาหมอย': 'ᨡ᩠ᨶᨲᩣᩉ᩠ᨾᩬᨿ',
    'ซ่อน': 'ᨪᩬ᩵ᨶ',
    'ตุ๊ปู่,ตุ๊ลุง,ตุ๊อุ๊ย': 'ᨲᩩ᩶ᨸᩪᨲᩩ᩶ᩃᩩᨦᨲᩩ᩶ᩋᩩ᩶ᨿ',
    'ป่ามตอง': 'ᨸ᩵ᩣᨾᨲᩬᨦ',
    'ขาวผอน': 'ᨡᩣᩅᨼᩬᨶ',
    'สิกป่ก': 'ᩈᩥᨠᨸ᩵ᨠ',
    'เชือกกั้น': 'ᨩᩨᩋᨠᨠᩢ᩠ᨶ',
    'หอกใบคา': 'ᩉᩬᨠᩱᨷᨣᩣ',
    'ป่ง': 'ᨸᩫ᩵ᨦ',
    'นั่งหม้อแหม่': 'ᨶᩢ᩠ᨦᩉ᩠ᨾᩬᩯᩉ᩠ᨾ',
    'ฟักหม่น': 'ᨼᩢᨠᩉ᩠ᨾᩫᨶ',
    'สมยา': 'ᩈᩫᨾᨿᩣ',
    'ริน': 'ᩁᩥᨶ',
    'แผ้ว': 'ᩯᨹ᩶ᩅ',
    'สะเหล็กสะหน่อย': 'ᩈ᩠ᩃᩮᨠᩈᩉ᩠ᨶᩬᨿ',
    'งัน': 'ᨦᩢᨶ',
    'ก้าดีนก้าฮอน': 'ᨠ᩵ᨯᩦᨶᨠ᩵ᩣᩉᩬᨶ',
    'ก้าน': 'ᨠ᩶ᩣᨶ',
    'ซ้าเป้าซะหางควาย': 'ᨪ᩶ᩣᨸᩮᩢᩣᨪᩡᩉ᩠ᨦᩣᨿ᩠ᩅᩣᨿ',
    'ใส่แส่': 'ᩱᩈ᩵ᩯᩈ᩵',
    'น้ำหน่อ': 'ᨶ᩶ᩣᩴᩉ᩠ᨶᩬ᩵',
    'ก่อก..': 'ᨠᩬ᩵ᨠ',
    'เหลือเหื่อ': 'ᩉ᩠ᩃᩨᩋᩉ᩠ᩃᩨᩋ',
    'งาจ้าง': 'ᨦᩣᨩ᩶ᩣᨦ',
    'บึ่ง': 'ᨷᩧ᩠ᨦ',
    'เข้าเปี่ยน': 'ᨡ᩶ᩣᨸ᩠ᨿᨶ',
    'เสียมหลัว': 'ᩈ᩠ᨿᨾᩉ᩠ᩃᩅ',
    'เอ็ด': 'ᩮᩋ᩠ᨯ',
    'ป้อย ออกเสียง ป้อย': 'ᨸᩬ᩶ᨿ',
    'จ๋อย': 'ᨧᩬ᩶ᨿ',
    'ซะ': 'ᨪᩡ',
    'นอนตวย': 'ᨶᩬᨶᨲ᩠ᩅᨿ',
    'เหลี้ยม': 'ᩉ᩠ᩃ᩠ᨿ᩶ᨾ',
    'ละล่อย (กวี)': 'ᩃᩡᩃᩬ᩵ᨿ',
    'ดังจอง': 'ᨯᩢᨦᩬᨦ',
    'มดง่ามโบ้': 'ᨾᩫᨯᨦ᩵ᩣᨾᨷᩰ᩶',
    'กุ่มไก่': 'ᨠᩩ᩠ᨾᩱᨠ᩵',
    'กำเดียว': 'ᨠᩴ᩠ᨯ᩠ᨿᩅ',
    'ตามก๋ามัก': 'ᨲᩣᨾᨠᨾᩢᨠ',
    'อึนอือปือคอ': 'ᩋᩧᨶᩋᩨᨸᩨᩬ',
    'ฝูง': 'ᨼᩪᨦ',
    'แก้มแหลม': 'ᩡᨠ᩶ᨾᩉ᩠ᩃᩯᨾ',
    'กว๊าน': 'ᨠ᩠ᩅ᩶ᩣᨶ',
    'หยุก': 'ᩉ᩠ᨿᩩᨠ',
    'กิงเก๊าะเงาะ': 'ᨠᩥᨦᩡᨠ᩻ᩋᨦᩬᩡ',
    'สิบ': 'ᩈᩥᨷ',
    'เฮ่ย': 'ᩉᩮ᩵ᨿ',
    'ตก': 'ᨲᩫᨠ',
    'ไปเที่ยว': 'ᩱᨿᩯᩅ᩵',
    'เที่ยว': 'ᩋᩯ᩠᩵ᩅ',
    'ขี้แอ่ว': 'ᨡᩦ᩶ᩯᩅ᩵',
    'คนเลิง': 'ᨣᨶᩃᩮᩥᨦ',
    'คิง': 'ᨣᩥᨦ',
    'จะละเดิน': 'ᨧᩡᩃᩡᨯᩮ᩠ᨶ',
    'จิ๋มจิ๋มจิ๊ด': 'ᨧᩥᨾ᩺ᨧᩥᨾ᩺ᨧᩥ᩠ᨯ',
    'บ่กอง': 'ᨷ᩵ᨠᩬᨦ',
    'บืดๆ': 'ᨷᩨ᩠ᨯ᩺',
    'ปะแล็บๆ': 'ᨸᩡᩃᩯ᩠ᨷ᩺',
    'พาไปแอ่ว': 'ᨻᩣᩱᨿᩯᩅ᩵',
    'ไปแอ่ว': 'ᩱᨿᩯᩅ᩵',
    'หมาแอ่ว': 'ᩉ᩠ᨾᩯᩅ᩵',
    'ต้วนเดียว': 'ᨲ᩠ᩅᩫᨶᨯ᩠ᨿᩅ',
    'ต่างแอ่ว': 'ᨲᩣᨦᩯᩅ᩵',
    'ตึกๆ': 'ᨲᩧᨠ᩺',
    'เมาแอ่ว': 'ᩮᨾᩣᩯᩅ᩵',
    'ฮบแอ่ว': 'ᩉᩕᩫᨷᩯᩅ᩵',
    'ลวด': 'ᩃ᩠ᩅᨯ',
    'ล่า': 'ᩃ᩵ᩣ',
    'พี่': 'ᨸᩦ᩶',
    'น่ำ': 'ᨶ᩵ᩣᩴ',
    'ได้ก่า': 'ᩱᨯ᩶ᨠ᩵ᩣ',
    'ฝึก': 'ᨼᩥᨠ',
    'สุน': 'ᩈᩩᨶ',
    'จีบ': 'ᨧᩦᨷ',
    'จั๊บ': 'ᨧᩢᨷ',
    'ขอด': 'ᨡᩬᨯ',
    'ใส่จื้อ': 'ᩱᩈ᩵ᨧᩨ᩶',
    'คิมมิม': 'ᨣᩥᨾᨾᩥᨾ',
    'อาบหมาบ': 'ᩋᩣᨷᩉ᩠ᨾᩣᨷ',
    'ฮ้อน': 'ᩉᩕᩬᨶ',
    'หู': 'ᩉᩪ',
    'บ่หุม': 'ᨷ᩵ᩉᩩᨾ',
    'บ่านอยขม': 'ᨷ᩵ᩣᨶᩬᨿᨡᩫᨾ',
    'ใบพัน': 'ᩱᨷᨻᩢᨶ',
    'หลวง': 'ᩉ᩠ᩃᩅᨦ',
    'หุบหู่': 'ᩉᩩᨷᩉᩪ',
    'เอาตาย': 'ᩮᩋᩣᨲᩣᨿ',
    'ยั้งเย้า': 'ᨿᩢ᩠ᨦᩮᨿᩢᩣ',
    'ลดสองวง': 'ᩃᩫᨯᩈᩬᨦᩅᨦ',
    'ดวากๆ': 'ᨯ᩠ᩅᩣᨠ᩺',
    'โจ่โหว่': 'ᨧᩰ᩵ᩅᩰ᩵',
    'อวม': 'ᩋᩅᨾ',
    'เต้าเอว': 'ᨲᩮ᩶ᩣᩯᩋᩅ',
    'ผ่อบ่หัน': 'ᨹᩬ᩵ᨷ᩵ᩉᩢᨶ',
    'ปลูกต้นไม้': 'ᨸᩪᨠᨲᩫ᩶ᨶᨾᩲᶶ',
    'หญ้าหูหนวก': 'ᩉ᩠ᨿ᩶ᩣᩉᩪᩉ᩠ᨶᩅᨠ',
    'ลดก่า': 'ᩃᩫᨯᨠ᩵ᩣ',
    'จั่งก้อน': 'ᨧᩢ᩠ᨦᨠᩬᨶ',
    'หมูหาน': 'ᩉ᩠ᨾᩪᩉᩣᨶ',
    'ตาง': 'ᨲᩣᨦ',
    'ตกสะเกิ๊ด': 'ᨲᩫᨠᩈ᩠ᨠᩮᩥ᩠ᨯ',
    'จ่งฮ้าย': 'ᨧᩫ᩵ᨦᩉᩕᩣᨿ',
    'พร้าโต้': 'ᨻᩕᩣᨲᩰᶶ',
    'เก๊าะ': 'ᨠ᩻ᩋ',
    'ใส่เข้าตอกดอกไม้': 'ᩱᩈ᩵ᨡ᩶ᩣᨲᩋᨠᨯᩬᨠᨾᩲᶶ',
    'แมวควบ': 'ᩯᨾᩅᨣᩅᨷ',
    'กุ้มแอ้มข้าง': 'ᨠᩩ᩠ᨾᩯ᩠ᨾᨡᩣᨦ',
    'เหว่(ว สะกด)': 'ᩉ᩠ᩅᩯ',
    'ถัดนั้น/ถัดแต่นั้น': 'ᨳᩢᨯᨶᩢ᩠ᨶᨳᩢᨯᨲᩯ᩵ᨶᩢ᩠ᨶ',
    'สืบหูก': 'ᩈᩨᨷᩉᩪᨠ',
    'ก่าเหล้น': 'ᨠᩣᩉ᩠ᩃᩮ᩠ᨶ',
    'จะไปละไปขว้าง': 'ᨧᩡᩱᨿᩃᩡᩱᨿᨡᩅ᩶ᩣᨦ',
    'งุบ': 'ᨦᩩᨷ',
    'สิ่ว': 'ᩈᩥ᩵ᩅ',
    'ลีบเปลือกป้อ': 'ᩃᩦᨷᩮ᩠ᨸᩥᨠᨸᩬ᩶',
    'ยาผู่': 'ᨿᩣᨹᩪ᩵',
    'ต๋าวันแลง': 'ᨲᩣᩅᩢᨶᩯᩃᨦ',
    'ก๋าสะลองคำ': 'ᨠᩣᩈᩡᩃᩬᨦᨣᩣᩴ',
    'หน้าจ่าง': 'ᩉ᩠ᨶ᩶ᩣᨧ᩵ᩣᨦ',
    'โก่งโท่งโน่ง': 'ᨠᩰᨦᨴᩰᨦᨶᩰᨦ',
    'อ่อนแข็งอ่อนขา': 'ᩋᩬ᩵ᨶᩯᨡ᩠ᨦᨡᩣ',
    'ตูบน้อย': 'ᨲᩪᨷᨶᩬ᩵ᨿ',
    'เขี้ยวหี่': 'ᨡ᩶ᩦᨿᩅᩉᩦ',
    'แถมบ่าปอ': 'ᩯᨹ᩠ᨾᨷ᩵ᩣᨸᩬ',
    'จั๊กคาดตือเดือน': 'ᨧᩢᨠᨣᩣᨯᨲᩨᨯᩮᩥᨶ',
    'ป๋าจี่': 'ᨸᩣᨧᩦ᩵',
    'ผักเบี้ย': 'ᨹᩢᨠᨸ᩠ᨿᩡ',
    'เต็กนา': 'ᨲᩮ᩠ᨠᨶᩣ',
    'หนานปัญญา': 'ᩉ᩠ᨶᩣᨶᨸᨿ᩠ᨿᩣ',
    'อาบ': 'ᩋᩣᨷ',
    'ก่าผี': 'ᨠ᩵ᩣᨹᩦ',
    'เต่าเส่า': 'ᨲᩮ᩵ᩣᩈᩮ᩵ᩣ',
    'หอยดุด': 'ᩉᩬᨿᨯᩩᨯ',
    'ยอง': 'ᨿᩬᨦ',
    'หวีกๆ': 'ᩉ᩠ᨅᩦᨠ᩺',
    'ขมกิ๊ก': 'ᨡᩫᨾᨠᩥᨠ',
    'เปลวน้ำ': 'ᨸ᩠ᩃᩅᨶ᩶ᩣᩴ'
  };

  /// เลขโหรา (ใช้ทั่วไป)
  static const Map<String, String> horaNumbers = {
    '0': '᪐', '1': '᪑', '2': '᪒', '3': '᪓', '4': '᪔',
    '5': '᪕', '6': '᪖', '7': '᪗', '8': '᪘', '9': '᪙'
  };

  /// เลขธรรม (ใช้เฉพาะในคัมภีร์)
  static const Map<String, String> dhammaNumbers = {
    '0': '᪀', '1': '᪁', '2': '᪂', '3': '᪃', '4': '᪄',
    '5': '᪅', '6': '᪆', '7': '᪇', '8': '᪈', '9': '᪉'
  };
}
