CREATE TABLE IF NOT EXISTS `vocabulary_review` (
  `review_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `thai_word` VARCHAR(255) NOT NULL,
  `lanna_word` VARCHAR(512) NOT NULL,
  `reading` VARCHAR(512) NOT NULL,
  `meaning` TEXT NOT NULL,
  `senses_json` JSON NULL,
  `initial_letter` VARCHAR(8) NOT NULL,
  `proposed_category` VARCHAR(100) NOT NULL DEFAULT 'คำศัพท์ทั่วไป',
  `category_confidence` DECIMAL(5,4) NOT NULL DEFAULT 0,
  `category_status` ENUM('proposed', 'source_reviewed', 'expert_verified') NOT NULL DEFAULT 'proposed',
  `category_source` VARCHAR(100) NULL,
  `source_type` VARCHAR(50) NOT NULL,
  `source_id` VARCHAR(255) NOT NULL,
  `source_page` VARCHAR(100) NULL,
  `source_url` TEXT NULL,
  `pdf_evidence` JSON NULL,
  `verification_status` ENUM(
    'auto_checked_needs_expert',
    'source_image_verified',
    'owner_verified',
    'expert_verified',
    'verified_alias_to_source',
    'rejected'
  ) NOT NULL DEFAULT 'auto_checked_needs_expert',
  `source_search_status` ENUM(
    'source_image_verified',
    'reviewed_rejected',
    'candidate_pages_need_manual_review',
    'not_located_after_dual_ocr_needs_manual_review',
    'verified_alias_to_source'
  ) NOT NULL DEFAULT 'candidate_pages_need_manual_review',
  `source_search_note` TEXT NULL,
  `canonical_thai_word` VARCHAR(255) NULL,
  `canonical_lanna_word` VARCHAR(512) NULL,
  `alias_relation` VARCHAR(100) NULL,
  `review_note` TEXT NULL,
  `reviewed_by` VARCHAR(100) NULL,
  `reviewed_at` DATETIME NULL,
  `promoted_vocab_id` VARCHAR(20) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`review_id`),
  UNIQUE KEY `uq_vocab_review_source_pair` (`source_id`, `thai_word`, `lanna_word`),
  KEY `idx_vocab_review_initial_status` (`initial_letter`, `verification_status`),
  KEY `idx_vocab_review_source_search` (`initial_letter`, `source_search_status`),
  KEY `idx_vocab_review_canonical_thai` (`canonical_thai_word`),
  KEY `idx_vocab_review_category_status` (`proposed_category`, `category_status`),
  KEY `idx_vocab_review_thai` (`thai_word`),
  KEY `idx_vocab_review_promoted` (`promoted_vocab_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
